name: present_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  firebase_core: ^3.1.1
  firebase_storage: 12.1.0
  firebase_authentication: 0.0.28
  firebase_cloud_firestore: 5.0.1
  image_picker: 1.1.2
  convex_bottom_bar: 3.2.0
  intl: 0.19.0
  geolocator: 12.0.0
  geocoding: 3.0.0
  syncfusion_flutter_datepicker: 26.1.40
  syncfusion_flutter_core: 26.1.40
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

